#!/bin/bash
# Примеры использования исправленного Selenium код

echo "📚 ПРИМЕРЫ ИСПОЛЬЗОВАНИЯ ИСПРАВЛЕННОГО SELENIUM"
echo "=================================================="
echo ""

# Пример 1: Диагностика окружения
echo "1️⃣ ДИАГНОСТИКА (проверка Chrome/Selenium):"
echo "   python google_patents_parser/google_patents_parser.py --diagnose"
echo ""
echo "   Выведет:"
echo "   - Версию Python"
echo "   - ОС (Linux/Windows/macOS)"
echo "   - Статус selenium и webdriver-manager"
echo "   - Путь к ChromeDriver"
echo "   - Наличие Chrome/Chromium"
echo ""

# Пример 2: Диагностика с подробным логом
echo "2️⃣ ДИАГНОСТИКА С DEBUG ЛОГОМ:"
echo "   python google_patents_parser/google_patents_parser.py --diagnose --verbose"
echo ""
echo "   Выведет дополнительно DEBUG информацию"
echo ""

# Пример 3: Парсинг с Selenium (автоматический retry)
echo "3️⃣ ПАРСИНГ С SELENIUM (исправленный код):"
echo "   python google_patents_parser/google_patents_parser.py \\"
echo "     --url \"https://patents.google.com/patent/US1234567A\" \\"
echo "     --use-selenium"
echo ""
echo "   При ошибке Chrome автоматически:"
echo "   - Попробует --headless=new"
echo "   - Если не сработало, попробует --headless"
echo "   - Если не сработало, попробует минимальный набор опций"
echo ""

# Пример 4: Парсинг с Selenium + DEBUG лог
echo "4️⃣ ПАРСИНГ С SELENIUM И DEBUG ЛОГОМ:"
echo "   python google_patents_parser/google_patents_parser.py \\"
echo "     --url \"https://patents.google.com/patent/US1234567A\" \\"
echo "     --use-selenium \\"
echo "     --verbose"
echo ""
echo "   Выведет все попытки инициализации Chrome"
echo ""

# Пример 5: Парсинг без Selenium (быстро)
echo "5️⃣ ПАРСИНГ БЕЗ SELENIUM (через requests, быстрее):"
echo "   python google_patents_parser/google_patents_parser.py \\"
echo "     --url \"https://patents.google.com/patent/US1234567A\""
echo ""
echo "   Используется, если:"
echo "   - Selenium не работает"
echo "   - Нужна максимальная скорость"
echo ""

# Пример 6: Пакетный парсинг с Selenium
echo "6️⃣ ПАКЕТНЫЙ ПАРСИНГ С SELENIUM:"
echo "   # Создаём файл urls.txt"
echo "   cat > urls.txt << 'URLS'"
echo "   https://patents.google.com/patent/US1234567A"
echo "   https://patents.google.com/patent/US5234567B2"
echo "   URLS"
echo ""
echo "   # Запускаем парсинг"
echo "   python google_patents_parser/google_patents_parser.py \\"
echo "     --links-file urls.txt \\"
echo "     --output-dir ./patents \\"
echo "     --use-selenium \\"
echo "     --verbose"
echo ""

# Пример 7: При ошибке - что смотреть
echo "7️⃣ ЕСЛИ ОШИБКА SELENIUM:"
echo "   a) Запустите диагностику:"
echo "      python google_patents_parser/google_patents_parser.py --diagnose"
echo ""
echo "   b) Проверьте версии:"
echo "      pip show selenium webdriver-manager"
echo ""
echo "   c) Переустановите webdriver-manager:"
echo "      pip install --force-reinstall webdriver-manager"
echo ""
echo "   d) Используйте режим без Selenium:"
echo "      python google_patents_parser/google_patents_parser.py --url \"...\""
echo ""

# Пример 8: Помощь
echo "8️⃣ СПРАВКА ПО ПАРАМЕТРАМ:"
echo "   python google_patents_parser/google_patents_parser.py --help"
echo ""

echo "=================================================="
echo "✅ КЛЮЧЕВЫЕ УЛУЧШЕНИЯ В ИСПРАВЛЕННОМ КОДЕ:"
echo "=================================================="
echo ""
echo "1. 🔄 Множественные попытки инициализации Chrome"
echo "   - Пробует 3 варианта опций автоматически"
echo "   - Fallback на --headless если --headless=new не работает"
echo ""
echo "2. 📝 Подробное логирование"
echo "   - Логирует каждый этап инициализации"
echo "   - Показывает пути к ChromeDriver и версии"
echo ""
echo "3. 🔍 Функция диагностики"
echo "   - Флаг --diagnose проверяет окружение"
echo "   - Помогает выявить проблемы"
echo ""
echo "4. 🛡️ Лучшая обработка ошибок"
echo "   - Graceful shutdown драйвера"
echo "   - Понятные сообщения об ошибках"
echo ""
echo "5. 📊 Fallback механизм"
echo "   - Если Selenium не работает, автоматический fallback на requests"
echo ""

echo "=================================================="
echo "📚 ДОКУМЕНТАЦИЯ:"
echo "=================================================="
echo ""
echo "📖 SELENIUM_FIX.md      - Полное описание исправления"
echo "📖 QUICK_START.md       - Быстрый старт"
echo "📖 PATENT_PARSER_GUIDE.md - Полное руководство"
echo ""
